services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "5672:5672"
      - "15672:15672"
  
  kiosk-service:
    build:
      context: ./KioskService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - RabbitMQ__Host=rabbitmq
  
  display-service:
    build:
      context: ./DisplayService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - RabbitMQ__Host=rabbitmq
  
  loket-service:
    build:
      context: ./LoketService
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5003:5003"
    depends_on:
      - sqlserver
      - rabbitmq
